name: Discord Changelog (Embed)

on:
  push:
    branches:
      - master
      - dev
      - "release/**"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Debug (optionnel)
        run: |
          echo "EVENT PATH: $GITHUB_EVENT_PATH"
          test -f "$GITHUB_EVENT_PATH" && echo "✔ Fichier trouvé" || (echo "✖ Fichier manquant" && exit 1)

      - name: Build Discord embed payload
        id: payload
        shell: bash
        run: |
          # --- Données depuis le fichier d'événement fourni par GitHub ---
          REPO="${{ github.repository }}"
          BRANCH="${GITHUB_REF_NAME}"
          COMPARE_URL=$(jq -r '.compare' "$GITHUB_EVENT_PATH")
          ACTOR="${{ github.actor }}"
          AVATAR_URL="https://github.com/${ACTOR}.png?size=128"

          # Liste des commits (max 15), une ligne = message (sans \n), lien + auteur + sha court
          COMMITS=$(jq -r \
            '.commits[] |
              "- [" + (.message | gsub("\\n"; " ") | sub("\\s+$";"")) + "](" + .url + ") — **" + .author.name + "** (`" + (.id[0:7]) + "`)"' \
            "$GITHUB_EVENT_PATH" | head -n 15 )

          [ -z "$COMMITS" ] && COMMITS="(aucun message de commit fourni)"

          # Tronque à ~3500 chars pour rester safe avec la limite 4096 de Discord
          DESC="${COMMITS:0:3500}"

          TITLE="🚀 ${REPO} — push sur ${BRANCH}"
          COLOR=1907283
          TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

          # Construit le JSON final proprement avec jq
          jq -n \
            --arg username "GitHub → ${REPO}" \
            --arg avatar   "$AVATAR_URL" \
            --arg title    "$TITLE" \
            --arg url      "$COMPARE_URL" \
            --arg desc     "$DESC" \
            --arg branch   "$BRANCH" \
            --arg pusher   "$ACTOR" \
            --arg footer   "$REPO" \
            --arg ts       "$TS" \
            --argjson color $COLOR \
            '{
              username: $username,
              avatar_url: $avatar,
              embeds: [
                {
                  title: $title,
                  url: $url,
                  description: $desc,
                  color: $color,
                  fields: [
                    { name: "Branche", value: $branch, inline: true },
                    { name: "Auteur du push", value: $pusher, inline: true }
                  ],
                  footer: { text: $footer },
                  timestamp: $ts
                }
              ]
            }' > discord.json

      - name: Send embed to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -sS -X POST -H "Content-Type: application/json" \
               -d @discord.json "$DISCORD_WEBHOOK_URL"
